In [14]:
from blimp_class import kalman_blimp, imu_to_uwb, rotation_UWB, Rx, Ry,Rz
import numpy as np
import math
from numpy.linalg import norm

rotz = Rz(np.pi)

roty = Ry(np.pi/2)

rot = rotz@roty

print(rot)


[[-6.12323400e-17 -1.22464680e-16 -1.00000000e+00]
 [ 7.49879891e-33 -1.00000000e+00  1.22464680e-16]
 [-1.00000000e+00  0.00000000e+00  6.12323400e-17]]
